### ISSUE TITLE
Trying mysql -> csv and getting "ModuleNotFoundError: No module named 'MySQLdb'"

### ISSUE THREAD

**Issue by korlaxxalrok** [bruin-data/ingestr#8]
OS: `macOS 14.3.1`
Python: `3.11.8`
Installed via instructions of `pip install ingestr`

I'm getting `"ModuleNotFoundError: No module named 'MySQLdb'"` when I try mysql -> csv.

**Comment by karakanb** [comment]
this is happening due to MySQLdb being a system-wide dependency that needs to be installed in the host computer, which is not nice. pymysql driver doesn't have this problem, therefore you can solve this issue by changing your URI from `mysql://...` to `mysql+pymysql://...`.

I have released v0.2.1 which solves this issue and does this automatically for you.
